### ISSUE TITLE
Joyo American Sound Pedal [FEATURE]

### ISSUE THREAD

**Issue by jatinchowdhury18** [Chowdhury-DSP/BYOD#111]
Having trouble finding a circuit schematic for this one if anyone has any leads?

**Comment by michael-leroy** [comment]
Do you mean the Joyo "American Sound"? If so this is a copy of the tech21 blonde.

![image](https://user-images.githubusercontent.com/1274596/160944014-4d778807-29fa-4420-8a27-9eff8b31930f.png)

Might work pretty great as long as you eliminate the speaker cab simulation section.

**Comment by jatinchowdhury18** [comment]
Yes, I was thinking of [this pedal](https://www.joyoaudio.co.uk/JOYO-JF-14-american-sound-effect-pedal) in particular. From some internet research, it seems like the American Sound is closely related to the Sansamp Blonde. There's probably some history there that I'm unaware of.

Thanks for sharing the schematic, that will definitely be useful :)!
