### ISSUE TITLE
[BUG] Setting Yen Drive gain to 0% terminates plugin output

### ISSUE THREAD

**Issue by lamech** [Chowdhury-DSP/BYOD#127]
**Describe the bug**
Setting Yen Drive gain to 0% terminates plugin output.

**To Reproduce**
1. Instantiate a Yen Drive unit in the signal path.
2. Turn gain % all the way down.
3. Plugin output stops.
4. Can't get any sound out of the plugin without deleting it and starting again from scratch.

**Expected behavior**
Presumably gain should go to zero at 0% but when one turns it back up, or deletes the Yen Drive and replaces it with something else, or does anything else that would produce sound typically, the sound should come back.

**Screenshots**
[BYOD-yen-drive-0-crash.zip](https://github.com/Chowdhury-DSP/BYOD/files/8237640/BYOD-yen-drive-0-crash.zip)
1. Initial state, signal level is visible at both input and output. 
2. Instantiate Yen Drive in signal path, set gain to 0%. Output abruptly stops.
3. Delete Yen Drive unit and reconnect input to output. Output level stays at 0.
4. Add an oscilloscope showing input signal. Output level will stay at 0 until the plugin is deleted and reinstantiated.

**Desktop (please complete the following information):**
 - OS: MacOS 12.2.1
 - DAW Logic
 - Version 10.7.2

**Comment by jatinchowdhury18** [comment]
This bug has been fixed with #131. Thanks for reporting!
