### ISSUE TITLE
[BUG] VST2 reverts on project reload in REAPER

### ISSUE THREAD

**Issue by pauleye** [Chowdhury-DSP/BYOD#133]
**Describe the bug**
The VST2 version reverts to whatever preset is active when reloading a project. So for example if you start with the default (empty) preset, then add some modules and save your project, when reloading the project you'll be back at the empty default preset. Likewise if you pick a preset (user or built-in) and make some tweaks/additions to it, when reloading the project your setup will be reset to the chosen preset. The VST3 version doesn't do this.

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2 (64-bit)
 - DAW: REAPER
 - Version: 6.51 (64-bit)

**Comment by jatinchowdhury18** [comment]
Thanks for reporting this issue! Unfortunately, I have not been able to recreate the issue on my system. The only obvious difference is that I'm running a slightly newer version of Reaper (6.10). That makes me wonder if there may have been a bug in Reaper, which was later fixed.

Another thing that might be worthwhile would be to check the plugin log files, which can be found at `C:\Users\<username>\AppData\Roaming\ChowdhuryDSP\BYOD\Logs`. The logs should specifically show whenever the plugin is loading a preset, or adding/removing a processor or connection.

**Comment by pauleye** [comment]
I guess you mean to say you're running an _older_ version of REAPER; 6.10 (which is almost 2 years old now) on your system versus 6.51 (the current/latest version) on my system. Here are 2 logs from when creating the project/plugin and loading. Notice how the 2nd log has entries for "removing processor". The image I uploaded shows how it's supposed to look like, but when loading the project it's empty.
Link to the REAPER project: https://www.dropbox.com/s/8xdmoz4h0dq1vdh/BYOD-VST2-Test.rpp?dl=1
[BYOD_Log_2022-03-14_07-10-43.log](https://github.com/Chowdhury-DSP/BYOD/files/8241903/BYOD_Log_2022-03-14_07-10-43.log)
[BYOD_Log_2022-03-14_07-14-37.log](https://github.com/Chowdhury-DSP/BYOD/files/8241904/BYOD_Log_2022-03-14_07-14-37.log)
![BYOD-VST2-Test](https://user-images.githubusercontent.com/59901371/158110176-0cbccfd9-af7e-4cab-a7fc-8b52a4340c85.png)
.

**Comment by pauleye** [comment]
Here's 2 logs where I load the Jimi Hendrix preset, remove TS-Tone and Envelope Filter, then save the project, restart REAPER, and load the project. Something weird is going on when loading the project as the modules are created and removed several times. The end result is that the Jimi Hendrix preset is back at its normal state (TS-Tone and Envelope Filter not removed).
[BYOD_Log_2022-03-14_09-13-09.log](https://github.com/Chowdhury-DSP/BYOD/files/8242529/BYOD_Log_2022-03-14_09-13-09.log)
[BYOD_Log_2022-03-14_09-15-39.log](https://github.com/Chowdhury-DSP/BYOD/files/8242530/BYOD_Log_2022-03-14_09-15-39.log)

**Comment by pauleye** [comment]
And the Jimi test REAPER project: https://www.dropbox.com/s/zit6jg1agfdu3sq/BYOD-VST2-Test-Jimi.rpp?dl=1

**Comment by jatinchowdhury18** [comment]
Ah, I feel silly! Of course version 6.10 is older than version 6.51. After updating to version 6.51, I was able to recreate the issue. The log files are very helpful as well, so thanks for those!

**Comment by jatinchowdhury18** [comment]
This bug is now fixed with #137. The next nightly build will include the fix if you'd like to try it out!

**Comment by pauleye** [comment]
Yep, it works now, thanks for the quick fix :)
