### ISSUE TITLE
Reaper DAW-  Will not render properly in any setting over 2x oversampling[BUG]

### ISSUE THREAD

**Issue by Fyyry** [Chowdhury-DSP/BYOD#134]
**Describe the bug**
Using Reaper v6.51 DAW:
Rendering in OS Factor 1X = fine
Rendering in OS Factor 2X = fine
Rendering in anything 4x or more results in stuttering audio. You hear the dry guitar signal with intermittent spikes where you can hear the wet effected signal for a millisecond.

**To Reproduce**
1. Select online 1x/4x offline (or higher) (also tried 2x/4x) Had Reaper's asio set to 44.1 khz, 1024 samples buffer.
2. Click on File/render, offline render (tried all 3 options full speed offline (normal mode), 1 x offline, & 1 x offline render (idle))
3. Any os factor higher than 2x stutters between dry signal and wet signal rendered file.
Too bad, I can imagine the sound quality is better at those higher settings!

**Expected behavior**
Expected to run ok online at 1x, or 2x. OS Factor.
Expected the rendered audio file to render properly at any OS factor using offline render.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - DAW: Reaper v6.51
 - Version [e.g. 2.3]
 - 64 bit VST3 BYOD
 - Version: BYOD 1.0.0
 - 
Commit: 019606a on HEAD with JUCE version JUCE v6.1.5
Build: 9 Mar 2022 10:33 on fv-az211-942 with MSVC-19.29.30140.0
System: Windows (Desktop) with Windows 10 (64-bit) on 16 Core, Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
Plugin Info: VST3 running in Reaper running at 44.1 kHz with block size: 1024

 
If you are unsure about any of this information, please use the "Copy Diagnostic Info" tool in the plugin settings menu.

**Additional context**
Here's the preset if that helps:
[https://drive.google.com/file/d/1Td6MRHqLYLBYZQxuCWjVu8ziATQEcuQX/view?usp=sharing](url)

**Comment by jatinchowdhury18** [comment]
Thanks for reporting this, and especially for sharing the preset!

After a bit of investigation, it seems like the issue isn't so much that offline render has trouble at the higher sample rates, but that the "Metal Face" processor is not working correctly at the higher sample rate. Even more strangely, this issue only appears to be happening on Windows, and only in the plugin (not standalone). I'll keep investigating, and try to nail down exactly what's going on here.

Thanks!

**Comment by jatinchowdhury18** [comment]
Cool, this should be fixed now with #136. You can try it out in the next nightly build if you feel so inclined.

One thing to note with the Metal Face processor is that it may sound slightly different at different sample rates. This is within the realm of "expected" behaviour, since it's just part of how the algorithm works, but it is something to watch out for, if using a different "offline" oversampling rate.
