### ISSUE TITLE
[BUG] Potential Build Issue

### ISSUE THREAD

**Issue by GoodNoiseLLC** [Chowdhury-DSP/BYOD#140]
**Describe the bug**
I see a build issue with current master of BYOB and KlonCentaur source repo.  

**To Reproduce**
1. cmake -Bbuild
2. cmake --build build/ --config Release

**Expected behavior**
I see the same issue with building BYOB repo.  I can build the RTNeuralExample successfully and run in with Juce generated AudioPluginHost.

**Screenshots**  Here is the 
[ 26%] Building CXX object ChowCentaur/CMakeFiles/ChowCentaur.dir/GainStageML/GainStageMLProc.cpp.o
[ 26%] Building CXX object ChowCentaur/CMakeFiles/ChowCentaur.dir/GainStageML/RNNModel.cpp.o
[ 27%] Building CXX object ChowCentaur/CMakeFiles/ChowCentaur.dir/__/modules/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_utils.cpp.o
[ 28%] Building CXX object **ChowCentaur/CMakeFiles/ChowCentaur.dir/__/modules/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.o
error: Objective-C was disabled in PCH file but is currently enabled
1 error generated.**
make[2]: *** [ChowCentaur/CMakeFiles/ChowCentaur.dir/__/modules/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.o] Error 1
make[1]: *** [ChowCentaur/CMakeFiles/ChowCentaur.dir/all] Error 2
make: *** [all] Error 2

**Desktop (please complete the following information):**
 - OS: [MacOS 10.15.7 Catalina]
 - DAW [Juce AudioPluginHost AU/VST3 testing]
- Xcode 12.4 (12D4e)
- CMake 3.23.0-rc3

 
![KlonCentaurBuildError](https://user-images.githubusercontent.com/101018698/158433494-e04fec31-894c-4c18-b669-33c09b78fb15.png)
![Image 3-14-22 at 6 43 PM](https://user-images.githubusercontent.com/101018698/158433677-d418fc89-01c8-40fe-b4da-6d043dc9a557.jpg)

**Comment by jatinchowdhury18** [comment]
Ah thanks for reporting this!

When I compile on Mac, I usually use `Apple clang version 13.0.0 (clang-1300.0.29.30)`, I'd be curious to know if your compiler version is different (it should be available in the CMake logs)?

Another thing to try is to disable the pre-compiled headers, by commenting out [this line](https://github.com/Chowdhury-DSP/BYOD/blob/main/src/CMakeLists.txt#L105).

**Comment by GoodNoiseLLC** [comment]
I was able to build BYOD with success today!

 I pulled down the new v1.0.1 version today and used these commands to build:

If you'd like to make an optimized "release" build, it is suggested to use some slightly different build commands:

$ cmake -Bbuild -DCMAKE_BUILD_TYPE=Release
$ cmake --build build --config Release --parallel 4

I am using the same compiler that I saw build issues prior to v1.0.1 release.
Here is the output from CMake -Bbuild ... for today's build that worked:
Merrils-iMac:BYOD merrilbradshaw$ cmake -Bbuild -DCMAKE_BUILD_TYPE=Release
-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring juceaide
-- Building juceaide
-- Exporting juceaide
-- VERSION for JUCE: 6.1.5
-- RTNeural -- Using xsimd backend
-- Setting Clang compiler flags
-- Configuring BYOD headless
-- Found Git: /usr/bin/git (found version "2.24.3 (Apple Git-128)") 
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/merrilbradshaw/Programming/BYOD/build
Merrils-iMac:BYOD merrilbradshaw$ cmake --build build --config Release --parallel 4

**Comment by GoodNoiseLLC** [comment]
Closing this issue.

**Comment by jatinchowdhury18** [comment]
Awesome, glad to hear the build process is working!
