### ISSUE TITLE
Build Issue with Fedora

### ISSUE THREAD

**Issue by detectivekid** [Chowdhury-DSP/BYOD#198]
Have to compile from source since on Fedora. Followed your instructions as well as I could. Had to find distro-specific names for the dependencies, but as far as I'm aware I've managed to get them all. I make it to the **cmake --build build --parallel 4** command but keep getting an error. As follows:

gmake[2]: *** [modules/CMakeFiles/juce_plugin_modules.dir/build.make:370: modules/CMakeFiles/juce_plugin_modules.dir/chowdsp_utils/modules/plugin/chowdsp_plugin_utils/chowdsp_plugin_utils.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[2]: *** [modules/CMakeFiles/juce_plugin_modules.dir/build.make:342: modules/CMakeFiles/juce_plugin_modules.dir/chowdsp_utils/modules/gui/chowdsp_gui/chowdsp_gui.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:603: modules/CMakeFiles/juce_plugin_modules.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2

System info:
OS: Fedora Linux 36 (KDE Plasma) x86_64
Kernel: 5.19.10-200.fc36.x86_64
Shell: bash 5.1.16
DE: Plasma 5.25.5
CPU: Intel i7-4770K (8) @ 3.900GHz
GPU: NVIDIA GeForce GTX 770 

Let me know if you need any more info.

Also let me know if this is all on my end and pointless, don't want to be that guy who wastes your time because I don't know enough.

**Comment by jatinchowdhury18** [comment]
Thanks for sharing the issue! Looks like the issue was just a missing include in one of the submodules. Should be fixed wwith #205.
