### ISSUE TITLE
Drag and drop function - select and move multiple processors at once

### ISSUE THREAD

**Issue by kraeiyg** [Chowdhury-DSP/BYOD#253]
Hi, just thought this may be a nice UX enhancement. If it were possible to implement left-clicking and dragging on blank space making that selection box like one has on the desktop. And then, one can do actions on multiple processors at once, such as moving them as a group, deleting, replacing with cable etc.
Mainly, if one could do what you do with desktop shortcuts as in the photos below, I think that would be a tremendous time-saver
![image](https://user-images.githubusercontent.com/63149488/211135166-21cc0b92-9308-4d66-a6fa-e8cc312afa57.png)
![image](https://user-images.githubusercontent.com/63149488/211135175-8a538a82-2e5e-4830-877f-563c81d45199.png)

**Comment by jatinchowdhury18** [comment]
Yeah, this is a cool idea! I'm not sure that "Replace With Cable" would work for groups of processors at a time, but being able to move and delete groups of processors is definitely do-able. I'll have to think a bit about the implementation, but I think this will be really cool!

**Comment by jatinchowdhury18** [comment]
Hi there! Sorry it's taken me so long to get back to this. As of #291, it's now possible to select multiple processor editors, and move them around together, or delete them together. If you'd like to try it out, you can download the latest [nightly build](https://chowdsp.com/nightly.html#byod).

There's definitely still some fine-tuning to be done, so if you see anything that you'd like to be a little different, definitely let me know!
