### ISSUE TITLE
[BUG] JUCE submodule not on a branch

### ISSUE THREAD

**Issue by hfiguiere** [Chowdhury-DSP/BYOD#256]
This is a build / repository issue.

**Describe the bug**
 JUCE submodule commit is not on a branch
`v1.1.0`
![image](https://user-images.githubusercontent.com/114441/212425563-a4187b65-893e-41f1-ab37-77c7d9d6b6ee.png)

And on `main`
![image](https://user-images.githubusercontent.com/114441/212425663-5d9c15bc-792c-4541-98eb-e65ed46780cf.png)

**Additional context**

This issue is similar to this

https://github.com/Chowdhury-DSP/chowdsp_juce_dsp/issues/1

**Comment by jatinchowdhury18** [comment]
Oh, good catch! I've updated the `.gitmodules` file to point to the correct repository. (If you're working with your local clone of the repo, you might need to run a `git submodules sync` to get everything working right.)

**Comment by hfiguiere** [comment]
sadly this still preclude doing a 1.1.0 build without pain.

**Comment by jatinchowdhury18** [comment]
That's true, but I'll be tagging version 1.1.3 later today, so if you're okay with waiting for that version, then it won't be a problem for much longer.

By the way, do you know if there might be a way to adjust the [CI scripts](https://github.com/Chowdhury-DSP/BYOD/blob/main/.github/workflows/cmake.yml) to catch this sort of thing in the future?

**Comment by hfiguiere** [comment]
I can definitely wait for a 1.1.3 tag. There is no urgency.

**Comment by hfiguiere** [comment]
Just tested with `main`, it works ! thanks.
