### ISSUE TITLE
Mac standalone version input is silent

### ISSUE THREAD

**Issue by magillos** [Chowdhury-DSP/BYOD#263]
Stand-alone Mac version doesn't request microphone access, therefore input remains silent. Plug-in version works fine in Reaper.

**Comment by magillos** [comment]
The latest commit 71dfeef fixes the issue. Thank you very much!

**Comment by jatinchowdhury18** [comment]
Cool! Yeah, I did some investigating and was planning to update this issue after the new nightly builds were ready, but you already caught it. Thanks for the bug report!
