### ISSUE TITLE
[Question] How to set processor custom LookAndFeel?

### ISSUE THREAD

**Issue by butchwarns** [Chowdhury-DSP/BYOD#271]
Following the instructions given in the guide on creating a new processor, I ran into an issue trying to apply a custom `LookAndFeel`. The Readme states, that the `uiOptions.lnf` should be set, but it doesn't seem to be existent. In the processor base class I was able to find a virtual function, that might be the up-to-date way of doing this. Unfortunately I wasn't able to get it to work by just overriding the function and returning the lnf from the shared `lnfAllocator`. 

Could you maybe give me a hint on where I went wrong? 

Many thanks! 

-Butch

**Comment by jatinchowdhury18** [comment]
Hi Butch,

Apologies for not keeping the documentation up-to-date, I'll make sure that gets fixed shortly.

Overriding `BaseProcessor::getCustomLookAndFeel()` is the correct way to get a custom look and feel for your processor, and using the `SharedLNFAllocator` is the right thing to do as well.

My guess as to what's going on is that the methods being overridden in your custom `LookAndFeel` maybe aren't being used by the processor UI, so it seems like the lnf isn't being set? In particular, if you want to change how the sliders look for your processor, you're going to want to derive from [`ProcessorLNF`](https://github.com/Chowdhury-DSP/BYOD/blob/main/src/gui/utils/LookAndFeels.h#L21), and override the [`createSlider()`](https://github.com/Chowdhury-DSP/BYOD/blob/main/src/gui/utils/LookAndFeels.h#L37-L38) method.

If you're able to share a branch or some example code, I'd be happy to take a look at it!

**Comment by butchwarns** [comment]
Hi Jatin, 

thanks a lot for pointing me in the right direction! I think I got it now. 
I spent the weekend implementing a dual resonating four-pole filter based on the transistor-ladder structure - modeled virtual analog style by the topology-preserving transform method. 

If you feel like checking it out, it is here: 
[Ladder Filter BYOD Fork](https://github.com/butchwarns/BYOD-Ladder-Filter)

The processor itself is already fully there, just lacking some eye candy. (Will see what I can come up with after work.)

I would be more than happy to contribute the processor to the BYOD project, if it is something you can see being useful!

-Butch

**Comment by jatinchowdhury18** [comment]
Cool stuff! Yeah, the new processor would definitely be a welcome contribution. I was able to test out the changes on your fork today, and it's sounding quite nice :). Feel free to make a pull request whenever you're happy with it, and I can take a closer look at the code.

**Comment by butchwarns** [comment]
That's great to hear :) I will leave the GUI updates aside for when I find time and inspiration, but will create a PR for the processor as such now. And of course, feel free to tell me if anything needs changing or could be improved upon. Many thanks!
-Butch
