### ISSUE TITLE
[BUG]Unable to load IR

### ISSUE THREAD

**Issue by magillos** [Chowdhury-DSP/BYOD#277]
With the current git version, I can't load any external IR through AmpIR processor.

**To Reproduce**
1. Go to AMP IR processor
2. Click on 'load from file' and choose external IR wav file
3. See error 'Unable to load IR!' and 'the followinf IR file is not valid'

**Desktop:**
 - OS: LINUX
 - error present in stand-alone and plugins

Version: BYOD 1.1.5
Commit: b063e10 on main with JUCE version JUCE v7.0.5
Build: 25 Apr 2023 11:01 on uoou with GNU-12.2.1
System:  with Linux (64-bit) on 12 Core, AMD Ryzen 5 5500U with Radeon Graphics
Plugin Info: Standalone running in Unknown running at sample rate 48.0 kHz with block size 1024

**Comment by jatinchowdhury18** [comment]
Thanks for the quick report! Unfortunately, this is a little hard for me to debug at the moment, since I don't currently have a Linux setup with a GUI.

I've pushed a new commit a couple minutes ago which likely has the same issue, but the error messages should provide a bit more information, if you care to give it a try.

**Comment by magillos** [comment]
I updated to 40fef87 and the error message is pretty much the same with just added 'invalid format' info at the end.

**Comment by jatinchowdhury18** [comment]
Okay great that's very helpful... I think I should be able to debug the issue from there, but if you are able to share the WAV file that triggers the issue on your end that would be handy as well!

**Comment by magillos** [comment]
[OD-UK112-V30-DYN-57-P00-00a.zip](https://github.com/Chowdhury-DSP/BYOD/files/11327249/OD-UK112-V30-DYN-57-P00-00a.zip)
Here is an example IRS but the same issue occurs with any other wav file. 
I had to zip it as github complained. 

Thanks

**Comment by jatinchowdhury18** [comment]
No problem!
