### ISSUE TITLE
[BUG] Info box z-order might be too low.

### ISSUE THREAD

**Issue by kiwijam** [Chowdhury-DSP/BYOD#302]
Windows / not using OpenGL.

The processor's info box, including the 'close' button, can be obscured by accident. Maybe the info box should be highest in the z-order? Or maybe info boxes should automatically close on mouse click on any GUI element.

![infobox](https://github.com/Chowdhury-DSP/BYOD/assets/7322709/4e3d589e-6675-458a-aa26-ca59346a5ade)

**Comment by jatinchowdhury18** [comment]
Fixed with a054163177c76470e01319ad1e8474541774b8ed. Thanks!
