### ISSUE TITLE
[BUG] Cables too low in the z-order?

### ISSUE THREAD

**Issue by kiwijam** [Chowdhury-DSP/BYOD#303]
Not sure if this one's a bug! But processors can obscure cables, which gets really confusing in tightly packed setups.

**Comment by jatinchowdhury18** [comment]
When we were first implementing the cables in BYOD we tried having the cables be "on top" of the processors. Ultimately it became a bit too unwieldy especially in cases where the cables might overlap some of the important controls in the processor editors. We're currently exploring some other possibilities for helping to make tightly packed setups look a bit more organized.
