### ISSUE TITLE
[BUG] Modulation category missing from popup

### ISSUE THREAD

**Issue by kiwijam** [Chowdhury-DSP/BYOD#306]
When right-clicking on a cable, there is no 'Modulation' category in the popup.

**Comment by jatinchowdhury18** [comment]
When right-clicking on a cable, the popup menu only shows modules that have a single input port and a single output port. Any modules that support other routing options (including all the modules in the "Modulation" category) are intentionally not included in the list (see the code [here](https://github.com/Chowdhury-DSP/BYOD/blob/main/src/processors/ProcessorStore.cpp#L317)).
