### ISSUE TITLE
[FEATURE]  controlling synth with guitar

### ISSUE THREAD

**Issue by ositaunus** [Chowdhury-DSP/BYOD#309]
is there anything in the domain of machine learning for controlling a synth with a guitar, making a guitar sound like a synth, or turning the guitar signal into midi in a live setting?

**Comment by jatinchowdhury18** [comment]
Hello! I've seen a few systems intended for this kind of use-case, but nothing that I'm immediately familiar with. In general for doing audio-to-MIDI transcription, the [NeuralNote](https://github.com/DamRsn/NeuralNote) plugin is a good place to start, however it's currently not designed for real-time use.

In any case, this kind of feature is not currently within the scope of BYOD.
