### ISSUE TITLE
[BUG] clap-juce-extension submodule unreachable

### ISSUE THREAD

**Issue by hfiguiere** [Chowdhury-DSP/BYOD#328]
**Describe the bug**
THe clap-juce-extension submodule is unreachable because the commit is not on any branch.

**To Reproduce**
1. The flathub build. Logs https://buildbot.flathub.org/#/builders/19/builds/6969

**Expected behavior**

Git submodule update --recursive works

**Screenshots**

![image](https://github.com/Chowdhury-DSP/BYOD/assets/114441/142d3df8-04aa-46ab-9dc7-9fd42d8e53b1)

**Desktop (please complete the following information):**

**Additional context**

See #256

**Comment by hfiguiere** [comment]
Note that this doesn't happen when doing a regular git clone / udate.

but the risk is that the commit disappear as it gets garbage collected.

**Comment by jatinchowdhury18** [comment]
Thanks for the report! This should be fixed with b644c032cd5cdc2267598908d680b10b640bfc08 if you could confirm?
