### ISSUE TITLE
[FEATURE] Tube screamer: more diode range

### ISSUE THREAD

**Issue by ShibuyaCyana** [Chowdhury-DSP/BYOD#339]
**Is your feature request related to a problem? Please describe.**

I have a TS-like pedal with 5 diodes in parallel; it comes with better dynamic range than original TS, being transparent in low dynamic while still providing that kind of "diode-y" distortion with heavy strike. I spend long time trying to find a similar digital pedal, until today surprisingly realize it's already here in BYOD; Just extend some range and I should be able to get a (more) similar digital counterpart in DAW : )

**Describe the solution you'd like**

Simply more diodes for tubescreamer. Looks like it's in `Chowdhury-DSP/BYOD/src/processors/drive/diode_circuits/DiodeParameter.h`, but I'm not sure if also need to change somewhere else.

**Comment by jatinchowdhury18** [comment]
Very cool! Thanks for mentioning this.

It should be fine to make the diodes range larger, and you're, correct that the only thing we have to do is change the range defined [here](https://github.com/Chowdhury-DSP/BYOD/blob/main/src/processors/drive/diode_circuits/DiodeParameter.h#L37).

I should clarify that the diodes parameter controls the number of diodes that are anti-parallel, in series with each other (as in the diagram below). I'm not 100% sure if this is the same configuration as the pedal that you were referencing?
<img width="424" alt="Screen Shot 2024-01-02 at 9 45 21 AM" src="https://github.com/Chowdhury-DSP/BYOD/assets/13724188/260fb983-ffb0-4df1-91a9-77650b25dbad">

**Comment by ShibuyaCyana** [comment]
sadly I don't have that pedal at hand, all I know is that pedal is using a ”5 diode structure" to preserve dynamics. Comparing based on my memory, I'm sure I hear a similar improvement of dynamic "transparency" when comparing that pedal to an original TS, and when I turn up the # of diode in BYOD screamer, but without a head to head comparison I can't determine if I really need more range for that knob.

Searching around and I found a schematic like this:
![image](https://github.com/Chowdhury-DSP/BYOD/assets/39703247/0d5ed2e5-8ee4-4c58-8e6b-ac9fe4c28949)
[source](https://www.amstzone.org/Schematic/)

Maybe this is what my pedal actually using, since I'm already quite happy with the 3 diode setup in BYOD (I guess that means 3 diode pairs), then maybe my feeling of "I need more diodes" is only an illusion caused by numbers...
