### ISSUE TITLE
[FEATURE] magic_enum as git submodule

### ISSUE THREAD

**Issue by KottV** [Chowdhury-DSP/BYOD#5]
**Is your feature request related to a problem? Please describe.**
Hi,

In some build systems (OBS) fetching the code during build process is prohibited. So the only way is to download the sources from github recursively, archive them, then build it offline.

**Describe the solution you'd like**
Move fetching `magic_enum` from `cmake` to `.gitmodules`

**Comment by jatinchowdhury18** [comment]
Thanks @KottV, this is now fixed with #6.

**Comment by KottV** [comment]
Thank You!
