### ISSUE TITLE
[FEATURE] Gate module or built in gate within input module

### ISSUE THREAD

**Issue by IsaakCode** [Chowdhury-DSP/BYOD#58]
**Is your feature request related to a problem? Please describe.**
Please add input metering and a gate function (either built into the input module or as a separate module). This will help gain staging and starting with a clean slate, before going into the fantastic drive and tone shaping modules.

**Comment by jatinchowdhury18** [comment]
Yeah, these are both good ideas! I think it would make sense to actually split it into two features requests: one for metering in the input/output processors, the other for new gate and compressor modules (which I had been thinking about adding anyway).

Thanks!
