### ISSUE TITLE
[FEATURE] Separate online / offline quality modes 

### ISSUE THREAD

**Issue by IsaakCode** [Chowdhury-DSP/BYOD#60]
Please add preset-agnostic online- and offline quality (oversampling) settings in the final version (as in Chow Tape Model). It's one of the best features to have when running a slower machine: having no oversampling on during tracking and premixing, but knowing that when the tracks are rendered / exported they will receive the highest qualiy treatment automatically. Best of both worlds. Thanks Jatin!

**Comment by jatinchowdhury18** [comment]
Thanks, this is a good idea as well! Oversampling should already be preset-agnostic (please let me know if this is not the case!), but having separae options for online/offline oversampling would definitely be helpful!

**Comment by jatinchowdhury18** [comment]
This feature is now implemented with #69.
