### ISSUE TITLE
[FEATURE] Replace block button

### ISSUE THREAD

**Issue by KottV** [Chowdhury-DSP/BYOD#8]
**Describe the solution you'd like**
Hi!
It would be useful to have just a little button (near the "close" or "info") which acts as "replace this block with ..."
At present we have to remove the block then a add new one with **+** menu and then drag it in the right place.

**Comment by jatinchowdhury18** [comment]
Hi Konstantin! Yeah, this is definitely a good idea. I'm planning to re-work the current structure of adding/removing modules to allow for parallel processing, so I want to do that first, and then I can add this feature!
